Put https://localhost:7099/api/tickets/12
Content-Type: application/json

{
     "title": "Tentativa de alteração",
     "description": "Testando regra",
     "status": "Pending",
     "priority": "High"
}