Put https://localhost:7099/api/tickets/1
Content-Type: application/json

{
    "title": "Tarefa adicionada usando o service, DI e repository",
    "description": "Tarefa adicionada usando o service, DI e repository"
}